<a href="https://colab.research.google.com/github/Manomay15/Suggesting-Best-Courses-using-Sentiment-Analysis/blob/master/CountVectorizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Manomay/preprocessed.csv')

In [ ]:
data.head()

reviews  sentiment
0  Thank you so for this wonderful course. Thank ...          1
1                        Love all the tutors in this          1
2  Excellent any satisfying course for learning d...          1
3                                  Excellent content          1
4  Everything is awesome. Thank you Andrew sir. A...          1

In [ ]:
data['sentiment'].unique()

array([ 1, -1,  0])

In [ ]:
from sklearn.utils import resample
#create two different dataframe of majority and minority class 
df_majority = data[(data['sentiment']==1)] 
df_minority = data[(data['sentiment']!=1)] 
df_majority_dwnsampled = resample(df_majority, 
                                 replace=True,    
                                 n_samples= 81845, 
                                 random_state=42)  
# Combine majority class with upsampled minority class
df_dwnsampled = pd.concat([df_majority_dwnsampled, df_minority])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df_dwnsampled['reviews'], df_dwnsampled['sentiment'], test_size = 0.3)

In [ ]:
y_train.shape

(114570,)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(token_pattern= r'\b\w+\b')
train_matrix = vectorizer.fit_transform(x_train)
test_matrix = vectorizer.transform(x_test)

In [ ]:
vectorizer

CountVectorizer(token_pattern='\\b\\w+\\b')

In [ ]:
train_matrix.shape

(114570, 42116)

In [ ]:
x_train = train_matrix
x_test = test_matrix

In [ ]:
x_train.shape

(114570, 42116)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf = RandomForestClassifier()

In [ ]:
data.isna().sum()

reviews      0
sentiment    0
dtype: int64

In [ ]:
rf.fit(x_train, y_train)

RandomForestClassifier()

In [ ]:
rf.score(x_test, y_test)

0.9322430858213515

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
preds = rf.predict(x_test)

In [ ]:
print(classification_report(preds,y_test))

              precision    recall  f1-score   support

          -1       0.90      0.96      0.93      9487
           0       0.91      0.90      0.90     14793
           1       0.96      0.94      0.95     24822

    accuracy                           0.93     49102
   macro avg       0.92      0.93      0.93     49102
weighted avg       0.93      0.93      0.93     49102



In [ ]:
y_train.unique()

array([-1,  0,  1])

In [ ]:
x_train.shape

(114570, 42116)

In [ ]:
import pickle
pickle.dump(rf, open('/content/drive/MyDrive/Manomay/model/model.pkl', 'wb'))

In [ ]:
pickled_model = pickle.load(open('/content/drive/MyDrive/Manomay/model/model.pkl', 'rb'))
pickled_model.predict(x_train)

array([-1,  0,  1, ..., -1,  0, -1])

In [ ]:
import numpy as np
list_n = ['very good course', 'nice', 'bad', 'very bad']
# df = np.array(list_n)
tp = vectorizer.transform(list_n)

In [ ]:
pickle.dump(vectorizer, open("/content/drive/MyDrive/Manomay/model/vector.pkl","wb"))

In [ ]:
tp.shape

(4, 42116)

In [ ]:
import pickle
pickled_model = pickle.load(open('/content/drive/MyDrive/Manomay/model/model.pkl', 'rb'))

In [ ]:
x=pickled_model.predict(tp)

In [ ]:
np.unique(x, return_counts=True)

(array([-1,  1]), array([2, 2]))